Usability - Default sorting on the admin view all holidays screen - sort by status - show pending first
UnosquareBelfast/admin-web pull request #47
Opened 2019-02-27 08:16 UTC by paulmatchett

## Relevant Issues

https://trello.com/c/KsmFU7C7/13-usability-default-sorting-on-the-admin-view-all-holidays-screen-sort-by-status-show-pending-first

## Major Changes Made

* Updated list of holidays to be pending first, in date order
* Updated list of pending holidays to be in date order

## AC List

It would be useful if on the /admin/holidays screen it automatically sorted by Status and showed pending holidays first

2019-02-28 15:43 UTC, d1wilko requested changes
Code looks clean but I'm not convinced you have your linter is set up correctly? - can you confirm and then I can approve

2019-03-14 14:08 UTC, d1wilko requested changes
one change then good to approve :)

2019-03-14 14:08 UTC, d1wilko commented on src/utilities/holidayOrdering.js
> +};
need a new line at the bottom here :)

2019-03-14 14:12 UTC, paulmatchett commented on src/utilities/holidayOrdering.js
> +};
👍 New line added

2019-03-22 10:22 UTC, d1wilko approved these changes

2019-03-22 10:24 UTC, merged